name: PHP Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**' # Run on all branches for pull requests

jobs:
  test:
    name: PHP ${{ matrix.php-version }} Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['8.3', '8.4']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer

      - name: Install dependencies
        run: composer install --no-progress --no-suggest

      - name: Run Code Sniffer
        run: composer cs

      - name: Run PHPStan
        run: composer stan

      - name: Run Unit Tests
        run: composer unit
